### ISSUE TITLE
feat: New Katex Plugin, Supporting Markdown Input Rule,And Katex Inline,Katex Block

### ISSUE THREAD

**Issue by xinkeng0** [halo-sigs/richtext-editor#10]
Hi there,

I'd like to request a new feature for the project. Specifically, I would like to see a new Katex plugin that supports Markdown input rule, and support both in katex inline and katex block formats.

The current implementation of Katex in the project is great.However, its input usage, similar to that of video and audio, makes it difficult to support Katex inline mode.

I have made some draft-level changes already. You can clone this repository to verify.
https://github.com/gengxiaoxiaoxin/richtext-editor/tree/katex
- [x] 👌The most basic undo support
- [x] ✨Katex inline and block
- [x] 😅~~simple katex input popover~~ Toy-level.
- [x] 🥰 `$xxx$` and $$\s\n input rule
- [x] 🥰 `$xxx$` paste rule
- [x] 😁standard DOM.(block is div,inline is span)
- [x] 💥~~Component styles that match this repository.~~ will new PR
- [x] ❓~~Direct output of KatexRenderedHTML.(We need to discuss.)~~ 

Here are a simple input.
![image](https://user-images.githubusercontent.com/29268441/236775665-be8a368b-3f6b-4809-ad8f-1b952162f72d.png)
![image](https://user-images.githubusercontent.com/29268441/236777760-bece94bd-a303-4504-bbb8-670fd74d3627.png)

and the content is
```html
<p></p><div content="" data-block-katex="true"></div><p style="text-align: right">Did you see that?<span content="\int_{-\infty}^\infty \frac{e^{-x^2}}{\sqrt{\pi}} \, dx = 1" data-inline-katex="true"></span>Katex</p><div content="\int_{-\infty}^\infty \frac{e^{-x^2}}{\sqrt{\pi}} \, dx = 1" data-block-katex="true"></div>
```

Please let me know your thoughts on this request. Thank you for your time and consideration.

Best regards.

**Comment by ruibaby** [comment]
Nice work! 

I have tried your draft locally, there is a question:

How to implement rendering in the theme? Currently, i haven't observed any saved structure after Katex rendering, so should we use Katex library for rendering in the theme? I think it might be a bit inconvenient for end users.

BTW, you can submit a PR first.

**Comment by xinkeng0** [comment]
> How to implement rendering in the theme? Currently, i haven't observed any saved structure after Katex rendering, so should we use Katex library for rendering in the theme? I think it might be a bit inconvenient for end users.
> 
Currently, the plugin only exports the `<katex>` tag instead of the final KatexRenderedHTML. 
If we support exporting as KatexRenderedHTML, then the end user would not need to import the Katex library, but would still need the KatexCss.

First,I will try to use standard DOM instead of `<katex-inline>`.

**Comment by xinkeng0** [comment]
😁Some new changes have been made, and now the plugin will render `<katex-inline content='$1$'>$1$</katex-inline>` to minimally support the KaTeX Auto Render Extension.

🚧Regarding the direct export KaTeX-Rendered-HTML, the work is still being explored. 

One possible issue is that if such a complex DOM is rendered, it may not be very elegant for editors like Tiptap that are WYSIWYG. 

🤔Therefore, I think it might be possible to perform some additional processing on the content after exporting from Tiptap.

**Comment by xinkeng0** [comment]
> First,I will try to use standard DOM instead of `<katex-inline>`.

Now the plugin will render the DOM：
- block: `<div content="p^1" data-block-katex="true">$$p^1$$</div>`
- inline: `<span content="123" data-inline-katex="true">$123$</span>`

**Comment by xinkeng0** [comment]
Close, welcome to the new plugin. #14
