### ISSUE TITLE
feat: The new plugin-katex plugin.

### ISSUE THREAD

**Issue by xinkeng0** [halo-sigs/richtext-editor#14]
Referencing comment from https://github.com/halo-sigs/richtext-editor/pull/12#issuecomment-1569711021, let's discuss the new plugin! 

Need to implement two parts.
## richtext-editor-math-katex-plugin
An tiptap plugin that supports WYSIWYG math editing experience (similar to yuque).

## halo-math-plugin
An implementation of a plugin that renders math(katex or mathjax) in the browser.(wait https://github.com/halo-dev/halo/issues/4003)
Performance optimization: 
- [ ] On-demand Import based on article metadata.(exampl: mathjax=true or katex=true)

**Comment by ruibaby** [comment]
ideas for changes related to the editor:

Expect to define it in this way in the Halo plugin:

```ts
import { definePlugin } from "@halo-dev/console-shared";
import { KatexExtension } from "./extensions/katex";

export default definePlugin({
  extensionPoints: {
    "editor:default:extension": () => {
      return [
        KatexExtension
      ];
    },
  },
});
```

Therefore, this editor may need to support the definition of action bar items, Slash Command items, etc. in the Extension, such as:

```ts
export const ExtensionKatexInline = Node.create({
  name: "KatexInline",

  addAttributes() {},

  parseHTML() {
    return [];
  },

  renderHTML({ HTMLAttributes }) {
    return [];
  },

  addNodeView() {
    return VueNodeViewRenderer(KatexRenderComponent);
  },

  addInputRules() {},
  addPasteRules() {},

  // add toolbars and slashCommands items definition
  addOptions() {
    return {
      ...this.parent?.(),
      toolbars: () => {
        return [
          // some toolbars
        ];
      },
      slashCommands: () => {
        return [
          // some toolbars
        ];
      },
    };
  },
});
```

**Comment by xinkeng0** [comment]
> ideas for changes related to the editor:
> 
> Expect to define it in this way in the Halo plugin:
> 
> ```ts
> import { definePlugin } from "@halo-dev/console-shared";
> import { KatexExtension } from "./extensions/katex";
> 
> export default definePlugin({
>   extensionPoints: {
>     "editor:default:extension": () => {
>       return [
>         KatexExtension
>       ];
>     },
>   },
> });
> ```
> 
Regarding the plugin section, are the plugins installed online? If so, the plugins need to be pre-packaged。

**Comment by ruibaby** [comment]
> Regarding the plugin section, are the plugins installed online? If so, the plugins need to be pre-packaged。

You can refer to: https://github.com/halo-sigs/plugin-bytemd

Document:

- https://docs.halo.run/user-guide/plugins
- https://docs.halo.run/developer-guide/plugin/introduction

**Comment by xinkeng0** [comment]
> You can refer to: https://github.com/halo-sigs/plugin-bytemd
> 
> Document:
> 
> * https://docs.halo.run/user-guide/plugins
> * https://docs.halo.run/developer-guide/plugin/introduction

Okay. So it looks like I can start working on task **halo-math-plugin** after https://github.com/halo-dev/halo/issues/4003 is done. This way, all instances of  $x^2$  in the article will render correctly.

**Comment by ruibaby** [comment]
I have verified it based on https://github.com/halo-dev/halo/pull/4080 and https://github.com/halo-sigs/richtext-editor/pull/16, and it works properly.

Next, we will further improve some details. Then we can create a repository for the Katex plugin.

![image](https://github.com/halo-sigs/richtext-editor/assets/21301288/12e13e5c-a44d-46ef-b687-1b829bc304b5)
![image](https://github.com/halo-sigs/richtext-editor/assets/21301288/68343ea6-5350-4735-a016-3ac49c717c31)
![image](https://github.com/halo-sigs/richtext-editor/assets/21301288/af59150a-30a3-455f-95bf-ef2d997f8147)
![image](https://github.com/halo-sigs/richtext-editor/assets/21301288/d1628e5d-f62d-48a2-94ac-3a584e11b82f)
