### ISSUE TITLE
修改各个 Block 的参数设置形式

### ISSUE THREAD

**Issue by ruibaby** [halo-sigs/richtext-editor#18]
目前编辑器对于某些自定义的内容块提供了一些参数设置，目前的设置方式是将鼠标悬浮到某个内容块，然后以 popper 的方式弹出，但目前发现这种方式不是特别方便，而且很容易误操作，对于定位也不是很好处理，所以期望进行优化。

<img width="1307" alt="image" src="https://github.com/halo-sigs/richtext-editor/assets/21301288/ee8bfa2b-7fea-4c07-a6a0-c6d5453d8e5b">

我的建议：

1. 方案一：在内容块顶部添加固定设置区域，在聚焦或者炫富的时候显示。
2. 方案二：在内容块右上角提供设置按钮，点击之后弹出下拉框显示参数设置区域。

/kind improvement

**Comment by xinkeng0** [comment]
个人意见，支持方案一。
Focus之后，顶部出现相对元素固定位置的操作栏。
