### ISSUE TITLE
指令列表中的搜索功能不能使用中文搜索

### ISSUE THREAD

**Issue by wan92hen** [halo-sigs/richtext-editor#21]
使用 `列表` 关键字进行搜索时没有结果，需要使用 `list` 关键字进行搜索。
![image](https://github.com/halo-sigs/richtext-editor/assets/27671436/986a3b47-593b-4dbc-a95f-7cd26aa6beef)
![image](https://github.com/halo-sigs/richtext-editor/assets/27671436/949478e0-eef6-4d83-9a94-b605a80d3e9e)

**Comment by hilaliu** [comment]
编辑器是支持中文的，需要使用拼音。
<img width="1438" alt="image" src="https://github.com/halo-sigs/richtext-editor/assets/110895612/f7f08da4-5876-497e-9bde-3696c61bf49d">

**Comment by ruibaby** [comment]
/close

此仓库即将归档，后续如果还有该问题，可以在 https://github.com/halo-dev/halo 中重新提交。
