### ISSUE TITLE
在表格内添加行列图标很难点到

### ISSUE THREAD

**Issue by wan92hen** [halo-sigs/richtext-editor#60]
如图所示，在 [2.10.0-alpha.1](https://github.com/halo-dev/halo/releases/tag/v2.10.0-alpha.1) 中，基本点不中添加行列的图标。
但是使用当前仓库 vercel 自动部署的地址是可以比较正常的操作的。
![msedge_xhDgwzZN64](https://github.com/halo-sigs/richtext-editor/assets/27671436/d6fc597a-a5c0-43a7-b5a3-2d6f1b0b485f)

**Comment by JohnNiang** [comment]
我这里无法复现。

Halo 版本：2.10.0。
