### ISSUE TITLE
增加对冒泡菜单扩展追加扩展的能力

### ISSUE THREAD

**Issue by LIlGG** [halo-sigs/richtext-editor#65]
在 https://github.com/halo-sigs/richtext-editor/pull/38 中对冒泡菜单的扩展方式进行了重构。

但根据实际体验，还需要增加在已扩展的插件上面再次进行追加扩展的方式。

例如在 Text 扩展中，增加了冒泡菜单的扩展。但其余用户可能会在某个编辑器插件中，对 Text 扩展的冒泡菜单进行二次扩展，例如增加一个额外的功能框、额外控制是否显示 Text 的冒泡菜单等。

/kind improvement

**Comment by ruibaby** [comment]
hi @LIlGG 此仓库即将归档，稍后我会将此 issue 手动转移到 halo-dev/halo

/close
