### ISSUE TITLE
feat: Revert the changes made in #2 to support ImageViewResizing.

### ISSUE THREAD

**Issue by xinkeng0** [halo-sigs/richtext-editor#8]
Revert the changes made in #2.
Avoid conflicts with manual size setting caused by immediate triggering after binding by checking the number of ResizeObserver events triggered.
Remove the transition of the Image component (or at least remove the width and height) to avoid the blocking feeling caused by resizing.
The example has been updated accordingly. You can clone this repository to verify.

https://github.com/gengxiaoxiaoxin/richtext-editor

If the review passes, I would be happy to submit a PR.

![image](https://user-images.githubusercontent.com/29268441/234774231-ddd4af18-54df-4afc-834b-65108e6d331f.png)
![image](https://user-images.githubusercontent.com/29268441/234774309-dc698c55-7cc8-43c0-b9e9-eefb5ee0dfc3.png)

**Comment by ruibaby** [comment]
I've tried your changes and it's great.

PR Welcome!
